#!/usr/bin/env bash
# setup_env.sh — Recorder env-var bootstrapper.
#
# Usage:
#   source scripts/setup_env.sh           # export LERO_* in current shell from .env + defaults
#   bash   scripts/setup_env.sh --check   # print resolved values, exit
#   bash   scripts/setup_env.sh --detect  # autodetect ports/camera, write .env (interactive)
#   bash   scripts/setup_env.sh --help
#
# Behaviour:
#   - Idempotent. Pre-set env vars are never overwritten.
#   - Loads .env (repo root) into the environment if present.
#   - Defaults only kick in when neither shell env nor .env supply a value.
#
# Variables managed:
#   LERO_FOLLOWER_PORT  — SO-101 follower serial port (required for recording).
#   LERO_LEADER_PORT    — SO-101 leader serial port (optional; teleop only).
#   LERO_CAM_SERIAL     — RealSense D435 serial (optional; "" / AUTO = first device).
#
# This script is also wired into [activation] in pixi.toml, so entering the
# pixi env via `pixi shell` or `pixi run` automatically applies it.

set -u

_setup_env_log() { echo "[setup_env] $*"; }
_setup_env_err() { echo "[setup_env] ERROR: $*" >&2; }

# --- repo root -------------------------------------------------------------
_THIS_FILE="${BASH_SOURCE[0]:-$0}"
_THIS_DIR="$(cd "$(dirname "${_THIS_FILE}")" && pwd)"
_REPO_ROOT="$(cd "${_THIS_DIR}/.." && pwd)"

# --- .env loader -----------------------------------------------------------
_ENV_FILE="${_REPO_ROOT}/.env"
if [ -f "${_ENV_FILE}" ]; then
    while IFS= read -r _line || [ -n "${_line}" ]; do
        case "${_line}" in
            ''|\#*) continue ;;
        esac
        _key="${_line%%=*}"
        _val="${_line#*=}"
        _val="${_val%\"}"; _val="${_val#\"}"
        _val="${_val%\'}"; _val="${_val#\'}"
        if [ -z "$(eval "echo \${${_key}:-}")" ]; then
            eval "export ${_key}=\"${_val}\""
        fi
    done < "${_ENV_FILE}"
fi

# --- defaults --------------------------------------------------------------
# LERO_FOLLOWER_PORT default: leave unset (config.py falls back to /dev/ttyUSB0).
# LERO_LEADER_PORT, LERO_CAM_SERIAL: optional, no default.

# --- autodetect helpers ----------------------------------------------------
_detect_first_tty() {
    # Echo first matching tty path; empty if none.
    for _p in /dev/ttyACM* /dev/ttyUSB*; do
        [ -e "${_p}" ] || continue
        echo "${_p}"
        return 0
    done
    return 1
}

_detect_rs_serial() {
    # Try via python+pyrealsense2; echo first serial found, else empty.
    python3 - <<'PY' 2>/dev/null || true
try:
    import pyrealsense2 as rs
    ctx = rs.context()
    devs = list(ctx.query_devices())
    if devs:
        print(devs[0].get_info(rs.camera_info.serial_number))
except Exception:
    pass
PY
}

# --- summary ---------------------------------------------------------------
_print_summary() {
    _setup_env_log "LERO_FOLLOWER_PORT = ${LERO_FOLLOWER_PORT:-<unset; default /dev/ttyUSB0>}"
    _setup_env_log "LERO_LEADER_PORT   = ${LERO_LEADER_PORT:-<unset; optional>}"
    _setup_env_log "LERO_CAM_SERIAL    = ${LERO_CAM_SERIAL:-<unset; AUTO>}"
    _setup_env_log ".env file          = ${_ENV_FILE}$( [ -f "${_ENV_FILE}" ] && echo "" || echo " (missing)" )"
}

# --- detect / write mode ---------------------------------------------------
_run_detect() {
    _setup_env_log "Autodetecting hardware..."
    local _ports _follower _leader _cam
    mapfile -t _ports < <(ls /dev/ttyACM* /dev/ttyUSB* 2>/dev/null || true)
    if [ "${#_ports[@]}" -eq 0 ]; then
        _setup_env_err "no /dev/ttyACM* or /dev/ttyUSB* devices found (USB unplugged?)"
        _follower=""
        _leader=""
    else
        _follower="${_ports[0]}"
        _setup_env_log "follower candidate: ${_follower}"
        if [ "${#_ports[@]}" -ge 2 ]; then
            _leader="${_ports[1]}"
            _setup_env_log "leader candidate:   ${_leader}"
        else
            _leader=""
            _setup_env_log "leader candidate:   <none> (only one tty present)"
        fi
        if [ "${#_ports[@]}" -gt 2 ]; then
            _setup_env_log "extra ttys ignored: ${_ports[*]:2}"
        fi
    fi

    _cam="$(_detect_rs_serial | head -n1)"
    if [ -n "${_cam}" ]; then
        _setup_env_log "camera serial:      ${_cam}"
    else
        _setup_env_log "camera serial:      <none> (pyrealsense2 missing or no device)"
    fi

    # Pre-existing values win.
    _follower="${LERO_FOLLOWER_PORT:-${_follower}}"
    _leader="${LERO_LEADER_PORT:-${_leader}}"
    _cam="${LERO_CAM_SERIAL:-${_cam}}"

    if [ -z "${_follower}" ]; then
        _setup_env_err "cannot write .env: LERO_FOLLOWER_PORT unresolvable."
        return 1
    fi

    _setup_env_log "writing ${_ENV_FILE}"
    {
        echo "# robot-data-recorder env — generated by scripts/setup_env.sh --detect"
        echo "# Edit freely. Lines starting with # are ignored."
        echo "LERO_FOLLOWER_PORT=${_follower}"
        [ -n "${_leader}" ] && echo "LERO_LEADER_PORT=${_leader}" || echo "# LERO_LEADER_PORT=/dev/ttyACM1"
        [ -n "${_cam}" ]    && echo "LERO_CAM_SERIAL=${_cam}"    || echo "# LERO_CAM_SERIAL=123456789012"
    } > "${_ENV_FILE}"
    _setup_env_log "done. Run 'source scripts/setup_env.sh' (or restart pixi shell) to load."
}

# --- subcommand dispatch ---------------------------------------------------
_is_sourced=0
if [ "${BASH_SOURCE[0]:-}" != "${0:-}" ]; then
    _is_sourced=1
fi

if [ "${_is_sourced}" -eq 1 ]; then
    _print_summary
else
    _mode="${1:-}"
    case "${_mode}" in
        ''|--check)
            _print_summary
            ;;
        --detect)
            _run_detect || exit 1
            _print_summary
            ;;
        --help|-h)
            sed -n '2,15p' "${_THIS_FILE}"
            ;;
        *)
            _setup_env_err "unknown flag: ${_mode}"
            exit 2
            ;;
    esac
fi

set +u
